### ISSUE TITLE
UI in 19 lines

### ISSUE THREAD

**Issue by rochacbruno** [cuducos/not-my-ex#2]
I added a simple UI so I am sharing it here:

Requirements:
- [YAD](https://yad-guide.ingk.se/#_what_is_yad)
- AWK
- not-my-ex

Saved this file `~/bin/post.sh`
```bash
#!/bin/bash

export NOT_MY_EX_BSKY_PASSWORD="....."
export NOT_MY_EX_BSKY_EMAIL=fooo@bar.com
export NOT_MY_EX_MASTODON_INSTANCE=https://social.me.com
export NOT_MY_EX_MASTODON_TOKEN=sfsdffsdgsdfgsdfgsdfgsdfgsdfgsdfg
export NOT_MY_EX_DEFAULT_LANG=pt

yad --title='Not My Ex' \
    --text='New Post:' \
    --form \
    --field='Text:TXT' \
    --field="Image:FL" \
    "" "" | while read line; do
      TEXT=`echo $line | awk -F'|' '{print $1}'`
      IMAGE=`echo $line | awk -F'|' '{print $2}'`

    if [ -n "$IMAGE" ]; then
        IMAGE_FRAGMENT="--images $IMAGE"
    fi

    not-my-ex -y "$TEXT" $IMAGE_FRAGMENT
done

```

Then I configured a global keyborad shortcut `Mod + P` to execute the script and then post.

![Screenshot_20240903_193007](https://github.com/user-attachments/assets/4ba8f96b-06bd-4816-a0ad-4c51cea47c25)

I could add more 4 image dialogs but I was lazy.

**Comment by cuducos** [comment]
Feel free to add a `contrib/` and some docs : ) I think a lot of people might like it!
